services:
  db:
    image: postgres:15
    container_name: tea_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: tea_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: tea_bot
    depends_on:
      - api
      - db
    env_file:
      - .env
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tea_pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
  pgadmin_data:
    driver: local
